version: '3'
services:
  app:
    image: "node:16-alpine"
    user: "node"
    working_dir: /home/goofi
    environment:
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
    volumes:
      - .:/home/goofi
    ports:
      - "3000:3000"
    command: "yarn dev"
